centro_salud_app/centro_salud_app/urls.py
from django.urls import path
from permisos import views

urlpatterns = [
    # Autenticación y navegación
    path('', views.signin, name='signin'),  # Página de inicio
    path('signup/', views.signup, name='signup'),  # Registro de usuario
    path('signin/', views.signin, name='signin'),  # Inicio de sesión
    path('signout/', views.signout, name='signout'),  # Cierre de sesión
    path('home/', views.home, name='home'),  # Página principal para usuarios autenticados

    # Gestión de usuarios (solo para administradores)
    path('user-management/', views.user_management, name='user_management'),  # Listado de usuarios
    path('user-management/create/', views.create_user, name='create_user'),  # Crear usuario
    path('user-management/edit/<int:user_id>/', views.edit_user, name='edit_user'),  # Editar usuario
    path('user-management/delete/<int:user_id>/', views.delete_user, name='delete_user'),  # Eliminar usuario

    # Listados de permisos
    path('regular-permissions/', views.regular_permission_list, name='regular_permission_list'),  # Listado de solicitudes de feriado legal
    path('admin-permissions/', views.admin_permission_list, name='admin_permission_list'),  # Listado de solicitudes de permiso administrativo
    path('compensation-requests/', views.compensation_request_list, name='compensation_request_list'),  # Listado de solicitudes de compensación de tiempo

    # Formularios de solicitud
    path('request-permission/', views.request_permission, name='request_permission'),  # Solicitud de feriado legal
    path('admin-permission-request/', views.admin_permission_request, name='admin_permission_request'),  # Solicitud de permiso administrativo
    path('compensation-request/', views.compensation_request, name='compensation_request'),  # Solicitud de compensación de tiempo

    # Detalles de permisos
    path('permissions/<int:permission_id>/', views.admin_permission_detail, name='admin_permission_detail'),  # Detalle de feriado legal
    path('regular-permissions/<int:permission_id>/', views.regular_permission_detail, name='regular_permission_detail'),  # Detalle de solicitud de feriado legal (usuario normal)
    path('admin-permissions/<int:permission_id>/', views.admin_permission_admin_detail, name='admin_permission_admin_detail'),  # Detalle de permiso administrativo
    path('compensation-requests/<int:request_id>/', views.compensation_request_detail, name='compensation_request_detail'),  # Detalle de compensación de tiempo

    # Otros
    path('my-permissions/', views.user_permission_status, name='user_permission_status'),  # Estado de mis solicitudes
    path('complete-profile/', views.complete_profile, name='complete_profile'),  # Completar perfil de usuario

    # Generación de PDF
    path('generate-user-permission-pdf/<int:permission_id>/', views.generate_user_permission_pdf, name='generate_user_permission_pdf'),  # PDF para usuario normal
    path('generate-permission-pdf/<int:permission_id>/', views.generate_permission_pdf, name='generate_permission_pdf'),  # PDF para administrador
    
    # Alias redundantes (Elimina estos si no son necesarios)
    path('user-permission-status/', views.user_permission_status, name='user_permission_status'),  # Alias adicional para estado de solicitudes
    
    path('mis-solicitudes/feriado/', views.user_permission_status_feriado, name='user_permission_status_feriado'),
    path('mis-solicitudes/administrativo/', views.user_permission_status_administrativo, name='user_permission_status_administrativo'),
    path('mis-solicitudes/compensacion/', views.user_permission_status_compensacion, name='user_permission_status_compensacion'),
    path('mis-solicitudes/<str:tipo>/', views.user_permission_status, name='user_permission_status'),
    
]

centro_salud_app/permisos/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    CARGO_CHOICES = [
        ('Dentista', 'Dentista'),
        ('Medico', 'Médico'),
        ('Quimico-Farmaceutico', 'Químico-Farmacéutico'),
        ('Asistente Social', 'Asistente Social'),
        ('Enfermera', 'Enfermera'),
        ('Kinesiologo', 'Kinesiólogo'),
        ('Matrona', 'Matrona'),
        ('Nutricionista', 'Nutricionista'),
        ('Psicologo', 'Psicólogo'),
        ('Tecnologo Medico', 'Tecnólogo Médico'),
        ('Fonoaudiologo', 'Fonoaudiólogo'),
        ('Terapeuta Ocupacional', 'Terapeuta Ocupacional'),
        ('Educadora de Parvulos', 'Educadora de Párvulos'),
        ('Profesor de Educacion Fisica', 'Profesor de Educación Física'),
        ('Abogado', 'Abogado'),
        ('Ingeniero en Informatica', 'Ingeniero en Informática'),
        ('Ingeniero en Prevencion de Riesgos', 'Ingeniero en Prevención de Riesgos'),
        ('Ingeniero en Administracion de Empresas', 'Ingeniero en Administración de Empresas'),
        ('Ingeniero Comercial', 'Ingeniero Comercial'),
        ('Contador Auditor', 'Contador Auditor'),
        ('TENS Enfermeria', 'TENS (Enfermería)'),
        ('TANS Administracion', 'TANS (Administración)'),
        ('Podologo', 'Podólogo'),
        ('Estadistico', 'Estadístico'),
        ('Programador', 'Programador/ Técnico en Computación'),
        ('Paramedico', 'Paramédico'),
        ('Secretaria', 'Secretaria'),
        ('Administrativos de Salud', 'Administrativos de Salud'),
        ('Auxiliar de Servicio', 'Auxiliar de Servicio'),
        ('Conductor', 'Conductor'),
        ('Estafeta', 'Estafeta'),
        ('Director de Consultorio', 'Director de Consultorio (CESFAM Arrau Méndez)'),
        ('Director de Departamento de Salud Municipal', 'Director de Departamento de Salud Municipal'),
    ]
    
    DEPARTAMENTO_CHOICES = [
        ('Posta de Salud Rural Villa Baviera', 'Posta de Salud Rural Villa Baviera'),
        ('Posta de Salud Rural Los Canelos', 'Posta de Salud Rural Los Canelos'),
        ('Posta de Salud Rural Bullileo', 'Posta de Salud Rural Bullileo'),
        ('Posta de Salud Rural Bajos de Huenutil', 'Posta de Salud Rural Bajos de Huenutil'),
        ('Posta de Salud Rural Catillo', 'Posta de Salud Rural Catillo'),
        ('Posta de Salud Rural Digua', 'Posta de Salud Rural Digua'),
        ('Posta de Salud Rural Monte Flor', 'Posta de Salud Rural Monte Flor'),
        ('Posta de Salud Rural San Alejo', 'Posta de Salud Rural San Alejo'),
        ('Posta de Salud Rural Talquita', 'Posta de Salud Rural Talquita'),
        ('Posta de Salud Rural Los Carros', 'Posta de Salud Rural Los Carros'),
        ('Posta de Salud Rural Perquilauquén', 'Posta de Salud Rural Perquilauquén'),
        ('Posta de Salud Rural La Orilla', 'Posta de Salud Rural La Orilla'),
        ('Posta de Salud Rural Fuerte Viejo', 'Posta de Salud Rural Fuerte Viejo'),
        ('Centro Comunitario de Salud Familiar Los Olivos', 'Centro Comunitario de Salud Familiar Los Olivos'),
        ('Centro de Salud Familiar Arrau Méndez', 'Centro de Salud Familiar Arrau Méndez'),
        ('SAR', 'SAR'),
        ('Hospital San José', 'Hospital San José'),
        ('Centro Comunitario de Salud Familiar Buenos Aires', 'Centro Comunitario de Salud Familiar Buenos Aires'),
        ('Departamento de Salud Municipal Parral', 'Departamento de Salud Municipal Parral'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField("Nombre completo", max_length=100)
    rut = models.CharField("RUT", max_length=12)
    position = models.CharField("Cargo", max_length=50, choices=CARGO_CHOICES, null=True, blank=True)
    establishment = models.CharField("Establecimiento", max_length=100, choices=DEPARTAMENTO_CHOICES, null=True, blank=True)
    permissions = models.CharField("Permisos", max_length=100, null=True, blank=True)
    firma = models.ImageField("Firma", upload_to='firmas/', null=True, blank=True)

    def __str__(self):
        return f"Perfil de {self.user.username}"


class PermissionRequest(models.Model):
    CARGO_CHOICES = UserProfile.CARGO_CHOICES
    DEPARTAMENTO_CHOICES = UserProfile.DEPARTAMENTO_CHOICES
    ESTADO_CHOICES = [
        ('pendiente', 'Pendiente'),
        ('completado', 'Completado')
    ]
    REQUEST_TYPE_CHOICES = [
        ('FERIADO', 'Solicitud de Feriado Legal'),
        ('ADMINISTRATIVO', 'Permiso Administrativo'),
        ('COMPENSACION', 'Compensación de Tiempo')
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    full_name = models.CharField("Nombre completo", max_length=100)
    rut = models.CharField("RUT", max_length=12)
    position = models.CharField("Cargo", max_length=50, choices=CARGO_CHOICES)
    establishment = models.CharField("Establecimiento", max_length=50, choices=DEPARTAMENTO_CHOICES)
    request_type = models.CharField("Tipo de Solicitud", max_length=20, choices=REQUEST_TYPE_CHOICES, default='FERIADO')
    number_of_days = models.PositiveIntegerField("Número de días")
    date_from = models.DateField("Fecha desde")
    date_to = models.DateField("Fecha hasta")
    period = models.CharField("Periodo", max_length=20)

    autorizado = models.BooleanField("Autorizado", default=False)
    anticipado = models.BooleanField("Anticipado", default=False)
    postergado = models.BooleanField("Postergado", default=False)
    additional_date_from = models.DateField("Fecha desde", null=True, blank=True)
    additional_date_to = models.DateField("Fecha hasta", null=True, blank=True)
    firma_funcionario = models.FileField("Firma del funcionario", upload_to='firmas/', null=True, blank=True)
    estado = models.CharField(max_length=10, choices=ESTADO_CHOICES, default='pendiente')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.full_name} - {self.number_of_days} días desde {self.date_from} - Estado: {self.estado}"


class PermissionRequestAdmin(models.Model):
    CARGO_CHOICES = UserProfile.CARGO_CHOICES
    DEPARTAMENTO_CHOICES = UserProfile.DEPARTAMENTO_CHOICES
    JORNADA_CHOICES = [
        ('Completa', 'Completa'),
        ('Mañana', 'Mañana'),
        ('Tarde', 'Tarde')
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    full_name = models.CharField("Nombre completo", max_length=100)
    rut = models.CharField("RUT", max_length=12)
    position = models.CharField("Cargo", max_length=50, choices=CARGO_CHOICES)
    establishment = models.CharField("Establecimiento", max_length=100, choices=DEPARTAMENTO_CHOICES)
    number_of_days = models.PositiveIntegerField("Número de días")
    date_from = models.DateField("Fecha desde")
    date_to = models.DateField("Fecha hasta")
    jornada = models.CharField("Jornada", max_length=50, choices=JORNADA_CHOICES, default='Completa')
    firma_funcionario = models.ImageField("Firma del funcionario", upload_to='firmas/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.full_name} - {self.position}"


class CompensationRequest(models.Model):
    CARGO_CHOICES = UserProfile.CARGO_CHOICES
    DEPARTAMENTO_CHOICES= UserProfile.DEPARTAMENTO_CHOICES

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    full_name = models.CharField("Nombre completo", max_length=100)
    rut = models.CharField("RUT", max_length=12)
    position = models.CharField("Cargo", max_length=50, choices=CARGO_CHOICES)
    establishment = models.CharField("Establecimiento", max_length=100, choices=DEPARTAMENTO_CHOICES)

    number_of_hours = models.PositiveIntegerField("Número de horas")
    date_from = models.DateField("Fecha desde")
    date_to = models.DateField("Fecha hasta")
    time_from = models.TimeField("Horario desde")
    time_to = models.TimeField("Horario hasta")
    firma_funcionario = models.FileField("Firma del funcionario", upload_to='firmas/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.full_name} - {self.number_of_hours} horas desde {self.date_from}"


class Permission(models.Model):
    REQUEST_TYPE_CHOICES = [
        ('feriado', 'Solicitud de Feriado Legal'),
        ('administrativo', 'Permiso Administrativo'),
        ('compensacion', 'Compensación de Tiempo'),
    ]

    full_name = models.CharField(max_length=100)
    rut = models.CharField(max_length=12)
    date_from = models.DateField()
    date_to = models.DateField()
    estado = models.CharField(max_length=20, default='pendiente')
    request_type = models.CharField(max_length=20, choices=REQUEST_TYPE_CHOICES, default='FERIADO')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.full_name} - {self.get_request_type_display()}"

centro_salud_app/permisos/templates/admin_permission_request.html
{% extends "base.html" %}

{% block title %}Solicitud de Permiso Administrativo{% endblock %}

{% block content %}
<div class="form-container">
    <h2>Solicitud de Permiso Administrativo</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Enviar Solicitud</button>
    </form>
</div>
{% endblock %}


centro_salud_app/permisos/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Centro de Salud{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>

<nav>
    <div>
        <a href="{% url 'home' %}">
            <img src="{% static 'img/logo.png' %}" alt="Logo Departamento de Salud" style="height: 80px;">
        </a>

        {% if user.is_authenticated %}
            <div class="dropdown">
                <a href="#">Solicitudes de Permiso</a>
                <div class="dropdown-content">
                    <a href="{% url 'request_permission' %}">Feriado Legal</a>
                    <a href="{% url 'admin_permission_request' %}">Permiso Administrativo</a>
                    <a href="{% url 'compensation_request' %}">Compensación de Tiempo</a>
                </div>
            </div>

            <div class="dropdown">
                <a href="#">Mis solicitudes</a>
                <div class="dropdown-content">
                    <a href="{% url 'user_permission_status' 'FERIADO' %}">Feriado Legal</a>
                    <a href="{% url 'user_permission_status' 'ADMINISTRATIVO' %}">Permiso Administrativo</a>
                    <a href="{% url 'user_permission_status' 'COMPENSACION' %}">Compensación de Tiempo</a>
                </div>
            </div>

            {% if user.is_staff %}
                <div class="dropdown">
                    <a href="#">Listado de Permisos</a>
                    <div class="dropdown-content">
                        <a href="{% url 'regular_permission_list' %}">Feriado Legal</a>
                        <a href="{% url 'admin_permission_list' %}">Permiso Administrativo</a>
                        <a href="{% url 'compensation_request_list' %}">Compensación de Tiempo</a>
                    </div>
                </div>
                <a href="{% url 'user_management' %}">Gestión de Usuarios</a>
            {% endif %}
        {% endif %}
    </div>
    
    <div class="nav-links">
        {% if user.is_authenticated %}
            <a href="{% url 'signout' %}">Cerrar Sesión</a>
        {% else %}
            <a href="{% url 'signin' %}">Iniciar Sesión</a>
        {% endif %}
    </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

</body>
</html>

centro_salud_app/permisos/templates/compensation_request.html
{% extends "base.html" %}

{% block title %}Solicitud de Compensación de Tiempo{% endblock %}

{% block content %}
<div class="form-container">
    <h2>Solicitud de Compensación de Tiempo</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Enviar Solicitud</button>
    </form>
</div>
{% endblock %}


centro_salud_app/permisos/templates/compensation_request_list.html
{% extends "base.html" %}

{% block title %}Listado de Solicitudes de Compensación de Tiempo{% endblock %}

{% block content %}
<div class="table-container">
    <h2>Listado de Solicitudes de Compensación de Tiempo</h2>
    <form class="search-form" method="GET" action="{% url 'compensation_request_list' %}">
        <input type="text" name="q" value="{{ query }}" placeholder="Buscar por nombre o RUT">
        <button type="submit">Buscar</button>
    </form>
    <table>
        <thead>
            <tr>
                <th>Nombre</th>
                <th>RUT</th>
                <th>Fecha Desde</th>
                <th>Fecha Hasta</th>
                <th>Horas</th>
                <th>Acciones</th>
                <th>Descargas</th>
            </tr>
        </thead>
        <tbody>
            {% for request in compensation_requests %}
            <tr>
                <td data-label="Nombre">{{ request.full_name }}</td>
                <td data-label="RUT">{{ request.rut }}</td>
                <td data-label="Fecha Desde">{{ request.date_from }}</td>
                <td data-label="Fecha Hasta">{{ request.date_to }}</td>
                <td data-label="Horas">{{ request.number_of_hours }}</td>
                <td data-label="Acciones"><a href="{% url 'compensation_request_detail' request.id %}">Ver/Editar</a></td>
                <td data-label="Descargas"><a href="{% url 'generate_permission_pdf' request.id %}">Descargar PDF</a></td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="7">No se encontraron solicitudes de compensación de tiempo.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

centro_salud_app/permisos/templates/complete_profile.html
{% extends "base.html" %}

{% block title %}Completar Perfil{% endblock %}

{% block content %}
<div class="form-container">
    <h2>Completar Perfil</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="full_name">Nombre completo:</label>
        {{ form.full_name }}
        
        <label for="rut">RUT:</label>
        {{ form.rut }}
        
        <label for="firma">Firma:</label>
        {{ form.firma }}
        
        <button type="submit">Guardar</button>
    </form>
</div>
{% endblock %}

centro_salud_app/permisos/templates/create_user.html
{% extends "base.html" %}

{% block title %}Crear Usuario{% endblock %}

{% block content %}
<h2>Crear Nuevo Usuario</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Crear Usuario</button>
</form>
<a href="{% url 'user_management' %}">Volver a la gestión de usuarios</a>
{% endblock %}

centro_salud_app/permisos/templates/delete_user.html
{% extends "base.html" %}

{% block title %}Eliminar Usuario{% endblock %}

{% block content %}
<h2>Eliminar Usuario</h2>
<p>¿Está seguro de que desea eliminar al usuario <strong>{{ user.username }}</strong>?</p>
<form method="POST">
    {% csrf_token %}
    <button type="submit">Eliminar</button>
    <a href="{% url 'user_management' %}">Cancelar</a>
</form>
{% endblock %}

centro_salud_app/permisos/templates/edit_user.html
{% extends "base.html" %}

{% block title %}Editar Usuario{% endblock %}

{% block content %}
<h2>Editar Usuario</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar Cambios</button>
</form>
<a href="{% url 'user_management' %}">Volver a la gestión de usuarios</a>
{% endblock %}

centro_salud_app/permisos/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>Bienvenido a la Página Principal</h1>
<p>Seleccione el listado o el formulario que desea ver:</p>

<div class="request-options">
    <a href="{% url 'regular_permission_list' %}" class="button">Listado de Solicitudes de Feriado Legal</a>
    <a href="{% url 'admin_permission_list' %}" class="button">Listado de Solicitudes de Permiso Administrativo</a>
    <a href="{% url 'compensation_request' %}" class="button">Formulario de Solicitud de Compensación de Tiempo</a>
</div>
{% endblock %}

centro_salud_app/permisos/templates/permission_pdf_template.html
<!-- permission_pdf_template.html -->
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; }
        h2 { text-align: center; }
        .table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        .table th, .table td { border: 1px solid black; padding: 8px; text-align: left; }
        .table th { background-color: #f2f2f2; }
    </style>
</head>
<body>
    <h2>Solicitud de Permiso</h2>
    <p><strong>Nombre:</strong> {{ permission.full_name }}</p>
    <p><strong>RUT:</strong> {{ permission.rut }}</p>
    <p><strong>Cargo:</strong> {{ permission.position }}</p>
    <p><strong>Establecimiento:</strong> {{ permission.establishment }}</p>
    <p><strong>Fecha Desde:</strong> {{ permission.date_from }}</p>
    <p><strong>Fecha Hasta:</strong> {{ permission.date_to }}</p>
    <p><strong>Número de Días:</strong> {{ permission.number_of_days }}</p>
    <p><strong>Periodo:</strong> {{ permission.period }}</p>
    <p><strong>Estado:</strong> {{ permission.get_estado_display }}</p>

    
    {% if permission.firma_funcionario %}
        <p><strong>Firma:</strong> <img src="{{ permission.firma_funcionario.url }}" alt="Firma" width="200"></p>
    {% endif %}
</body>
</html>

centro_salud_app/permisos/templates/regular_permission_detail.html
{% extends "base.html" %}

{% block title %}Detalle de Solicitud de Feriado Legal{% endblock %}

{% block content %}
<h2>Autorizar Solicitud de Feriado Legal</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar Cambios</button>
</form>
{% endblock %}



centro_salud_app/permisos/templates/request_permission.html
{% extends "base.html" %}

{% block title %}Solicitud de Feriado Legal{% endblock %}

{% block content %}
<div class="form-container">
    <h2>Solicitud de Feriado Legal</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Enviar Solicitud</button>
    </form>
</div>
{% endblock %}

centro_salud_app/permisos/templates/signin.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="login-container">
    <h2>Inicie Sesión</h2>
    
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{ form.username.label_tag }}
            {{ form.username }}
        </div>
        <div class="form-group">
            {{ form.password.label_tag }}
            {{ form.password }}
        </div>
        <button type="submit" class="btn-login">Iniciar Sesión</button>
    </form>

    {% if messages %}
        {% for message in messages %}
            <div class="login-message">{{ message }}</div>
        {% endfor %}
    {% endif %}

    {% if form.errors %}
        <div class="error-message">Nombre de usuario o contraseña incorrectos.</div>
    {% endif %}
</div>
{% endblock %}

centro_salud_app/permisos/templates/user_management.html
{% extends "base.html" %}

{% block title %}Gestión de Usuarios{% endblock %}

{% block content %}
<div class="table-container">
    <h2>Gestión de Usuarios</h2>
    <table>
        <thead>
            <tr>
                <th>Nombre Completo</th>
                <th>RUT</th>
                <th>Cargo</th>
                <th>Establecimiento</th>
                <th>Permisos</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.full_name }}</td>
                <td>{{ user.rut }}</td>
                <td>{{ user.position }}</td>
                <td>{{ user.establishment }}</td>
                <td>{{ user.permissions }}</td>
                <td class="action-buttons">
                    <a href="{% url 'edit_user' user.user.id %}">Editar</a> |
                    <a href="{% url 'delete_user' user.user.id %}" onclick="return confirm('¿Estás seguro de que deseas eliminar este usuario?');">Eliminar</a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="6">No hay usuarios registrados.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}